name: 'Xeel Report'
description: 'Runs a report on the current repository and sends it to Xeel'
author: 'Xeel, Inc.'

# Define your inputs here.
inputs:
  organization:
    description: 'The Xeel organization ID'
    required: true
  repository:
    description: 'The Xeel repository ID. Defaults to the current repository'
    required: false
  plugins:
    description: 'The plugins to use for the report, as a comma-separated list'
    required: false

runs:
  using: node20
  main: dist/index.mjs
