name: 'Xeel Report'
description: 'Runs a report on the current repository and sends it to Xeel'
author: 'Xeel, Inc.'

# Define your inputs here.
inputs:
  organization:
    description: 'The Xeel organization ID'
    required: true

runs:
  using: node20
  main: dist/index.js